FROM python:3.7-alpine

# set work directory
WORKDIR /model

COPY model.py .
COPY api.py .

ENV FLASK_APP=vader_API.py
ENV FLASK_RUN_HOST=0.0.0.0

# install dependencies
COPY requirements.txt .
RUN pip install -r requirements.txt

EXPOSE 5000

CMD ["python", "-m", "flask", "run", "--host=0.0.0.0"]