version: "3"
services:
  toxicity-server:
    build: backend/.
    container_name: api-toxicity
    ports:
      - "5000:5000"

  web-server:
    build: web/.
    container_name: web-toxicity
    ports:
      - "5001:5000"

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - "./prometheus.yml:/etc/prometheus/prometheus.yml"
      - "./rules.yml:/etc/prometheus/rules.yml"

  node_exporter:
    image: prom/node-exporter
    container_name: node-exporter
    ports:
      - "9100:9100"
    pid: host

  alertmanager:
    image: prom/alertmanager
    container_name: alertmanager
    ports:
      - "9093:9093"