version: "3"
services:
  toxicity-server:
    build: model/.
    container_name: api-toxicity
    ports:
      - "80:5000"

  web-server:
    build: web/.
    container_name: web-toxicity
    ports:
      - "5000:5000"