global:
  scrape_interval: 10s
  evaluation_interval: 10s
rule_files:
  - rules.yml
alerting:
  alertmanagers:
  - static_configs:
    - targets: ['alertmanager:9093']

scrape_configs:

  - job_name: prometheus
    static_configs:
      - targets: ['localhost:9090']

  - job_name: node
    static_configs:
      - targets: [ 'node-exporter:9100' ]

  - job_name: backend
    static_configs:
      - targets: ['api-toxicity:80']

  - job_name: frontend
    static_configs:
      - targets: ['web-toxicity:5000']