FROM python:3.7

# set work directory
WORKDIR /model

COPY model.py .
COPY api.py .

ENV FLASK_APP=api.py
ENV FLASK_RUN_HOST=0.0.0.0

# install dependencies
COPY requirements.txt .
RUN pip install -r requirements.txt

# copy model
#COPY toxic_original-c1212f89.ckpt /root/.cache/torch/hub/checkpoints/

EXPOSE 5000

CMD ["python", "-m", "flask", "run", "--host=0.0.0.0"]